### ISSUE TITLE
[FEATURE] Badge on the extension

### ISSUE THREAD

**Issue by VonKavalier** [skorotkiewicz/Licom#1]
First of all, that is a really cool projet, thank you for creating it :slightly_smiling_face: 

I'm opening this issue because I thought about a feature that could bring more people to use your extension.
What about a little badge on the extension that displays how much comments are on the page ? Kind of like the amount of ads blocked by uBlock Origin. If this is possible that would be a nice feature and uers won't end up forgetting that this extension exists :blush: 

I'm also wondering if the localhost page is shared by everyone :thinking: 

Anyway thanks again for this nice project of yours !

**Comment by skorotkiewicz** [comment]
> little badge on the extension that displays how much comments are on the page 

Thanks for the response!
Just working on this because someone suggested the exact same thing!

**Comment by skorotkiewicz** [comment]
Done: https://github.com/skorotkiewicz/Licom/commit/d36a84b055e861863fa5e8d2e72d60573b281cd7 :)
