### ISSUE TITLE
Server details

### ISSUE THREAD

**Issue by danielfleischer** [skorotkiewicz/Licom#2]
Very nice idea and implementation!

Can you give some details, maybe in the README, on how to run the server or how you run the server, just so we can understand the design, where the data is being saved, etc. 

Thank you very much!

**Comment by skorotkiewicz** [comment]
Thanks for your reply,

Probably today I will add information on how to set up Licom! :)

**Comment by skorotkiewicz** [comment]
> Very nice idea and implementation!
> 
> Can you give some details, maybe in the README, on how to run the server or how you run the server, just so we can understand the design, where the data is being saved, etc.
> 
> Thank you very much!

https://github.com/skorotkiewicz/Licom#developing-server
