### ISSUE TITLE
Show same comments on http/https

### ISSUE THREAD

**Issue by NinCollin** [skorotkiewicz/Licom#3]
This may be or may not be intentional, but http and https versions of webpages have different sets of comments (i.e commenting on http://blah.blah wont affect comments on https://blah.blah)

_Technically_  a website could have entirely different sites on http and https though, but I'd imagine that's relatively uncommon

**Comment by skorotkiewicz** [comment]
Thank you for your reply.

I have added a change that solves this problem: 

https://github.com/skorotkiewicz/Licom/commit/33e06ffdd60b54a00c71c893b4619e4ffdceef78
